(define (domain elevator)
  (:requirements :strips :typing)
  (:types floor passenger)
  (:predicates
    (at ?f - floor)
    (passenger-at ?p - passenger ?f - floor)
    (in-elevator ?p - passenger)
    (adjacent ?f1 - floor ?f2 - floor)
    (elevator-capacity-0)
    (elevator-capacity-1)
    (elevator-capacity-2)
    (elevator-capacity-3)
    (elevator-capacity-4)
    (elevator-capacity-5)
  )
  (:action move-up
    :parameters (?f1 - floor ?f2 - floor)
    :precondition (and (at ?f1) (adjacent ?f1 ?f2))
    :effect (and (at ?f2) (not (at ?f1)))
  )
  (:action move-down
    :parameters (?f1 - floor ?f2 - floor)
    :precondition (and (at ?f2) (adjacent ?f1 ?f2))
    :effect (and (at ?f1) (not (at ?f2)))
  )
  (:action in
    :parameters (?p - passenger ?f - floor)
    :precondition (and (at ?f) (passenger-at ?p ?f) (or (elevator-capacity-0) (elevator-capacity-1) (elevator-capacity-2) (elevator-capacity-3) (elevator-capacity-4)))
    :effect (and (in-elevator ?p) (not (passenger-at ?p ?f)) 
                  (when (elevator-capacity-0) (and (not (elevator-capacity-0)) (elevator-capacity-1)))
                  (when (elevator-capacity-1) (and (not (elevator-capacity-1)) (elevator-capacity-2)))
                  (when (elevator-capacity-2) (and (not (elevator-capacity-2)) (elevator-capacity-3)))
                  (when (elevator-capacity-3) (and (not (elevator-capacity-3)) (elevator-capacity-4)))
                  (when (elevator-capacity-4) (and (not (elevator-capacity-4)) (elevator-capacity-5)))
                 )
  )
  (:action out
    :parameters (?p - passenger ?f - floor)
    :precondition (and (at ?f) (in-elevator ?p) (or (elevator-capacity-0) (elevator-capacity-1) (elevator-capacity-2) (elevator-capacity-3) (elevator-capacity-4) (elevator-capacity-5)))
    :effect (and (passenger-at ?p ?f) (not (in-elevator ?p)) 
                  (when (elevator-capacity-1) (and (not (elevator-capacity-1)) (elevator-capacity-0)))
                  (when (elevator-capacity-2) (and (not (elevator-capacity-2)) (elevator-capacity-1)))
                  (when (elevator-capacity-3) (and (not (elevator-capacity-3)) (elevator-capacity-2)))
                  (when (elevator-capacity-4) (and (not (elevator-capacity-4)) (elevator-capacity-3)))
                  (when (elevator-capacity-5) (and (not (elevator-capacity-5)) (elevator-capacity-4)))
                 )
  )
)